[workspace]

[package]
name = "guest-mock-starter"
version = "0.3.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = "1.0.68"
risc0-zkvm = { version = "0.18", default-features = false, features = ["std"] }
risc0-zkvm-platform = "0.18"

serde = { version = "1.0.188", features = ["derive", "rc"] }


sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }
sov-mock-da = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }
sov-modules-stf-template = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }
sov-risc0-adapter = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "a8c36914770b66c6a499a478718a0c5c4dabddc6" }

stf-starter = { path = "../../../stf" }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }


[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3